Pile 1.15 handle logic circle progress view at progress view controller
randyefan/Pile-MC.1 pull request #12
Opened 2021-04-08 17:29 UTC by randyefan

2021-04-08 17:49 UTC, zeinrezky commented on Pile/Core Data Manager/CoreDataManager.swift
> +            if user.count == 0 {
biasakan pake ternary operation kalo kaya begini @randyefan 

return user.count == 0 ? nil : x

2021-04-08 17:57 UTC, randyefan commented on Pile/Core Data Manager/CoreDataManager.swift
> +            if user.count == 0 {
noted kak zein, besok di resolve:D

2021-04-08 17:58 UTC, zeinrezky requested changes

2021-04-08 17:58 UTC, zeinrezky commented on Pile/Module/Challenge Progress/ProgressViewController.swift
> +        //Title
bisa buat private func untuk configuration setup navigation @randyefan , jadi didload itu isinya wrapped function semua

2021-04-08 17:58 UTC, zeinrezky commented on Pile/Module/Challenge Progress/ProgressViewController.swift
> +        guard let dataProgressChallenge = CoreDataManager.shared.fetchAllChallengeToProgress() else {
nice

2021-04-08 17:58 UTC, zeinrezky commented on Pile/Module/Challenge Progress/ProgressViewController.swift
> +        cell.titleProgressChallenge.text = progressChallenge[indexPath.row].challenges.nama
seharusnya controller ga boleh update View, harusnya code line 40 yang assign value ke text nya ada di dalam cell nya sendiri, dari controller hanya kirim model / value ke cell nya, dan sisanya urusan cell untuk nge binding value ke object nya @randyefan

2021-04-08 17:58 UTC, zeinrezky commented on Pile/Module/Home/HomeViewController.swift
> +        userData = CoreDataManager.shared.fetchUser()
hati2 dengan willappear, kalo naro logic dan ada kemungkinan datasource belum siap akan crash, mending lebih aman di didappear @randyefan

2021-04-08 17:58 UTC, zeinrezky commented on Pile/Module/Home/HomeViewController.swift
> +
biasakan rapih, delete unnecessary space di line 45 kaya gini, terus ssebelum buka kurung biasakan ada space 1

2021-04-08 17:58 UTC, zeinrezky commented on Pile/Module/Home/HomeViewController.swift
> +
make sure semua proses yang berhubungan dengan update UI itu jalan di dalam main thread.

DispatchQueue.main.async {
 // semua code yang berhubungan dengan update UI 
}
@randyefan

2021-04-08 18:01 UTC, randyefan commented on Pile/Module/Challenge Progress/ProgressViewController.swift
> +        //Title
oke kak itu soalnya di handle member tim yang lain @zeinrezky

2021-04-08 18:02 UTC, randyefan commented on Pile/Module/Home/HomeViewController.swift
> +        userData = CoreDataManager.shared.fetchUser()
iya kak ini dari member tim lain juga, besok saya resolve @zeinrezky

2021-04-08 18:03 UTC, randyefan commented on Pile/Module/Home/HomeViewController.swift
> +
noted kak

2021-04-08 18:04 UTC, randyefan commented on Pile/Module/Home/HomeViewController.swift
> +
paham kak, nanti saya bantu sampaikan ke member yang handle task bersangkutan

2021-04-09 03:09 UTC, DheoGV commented on Pile/Module/Challenge Progress/ProgressViewController.swift
> +        cell.titleProgressChallenge.text = progressChallenge[indexPath.row].challenges.nama
oke ka udah dibenerin

2021-04-12 08:35 UTC, merged